export const translateLang3 = {
  RU: {
    location: 'Кыргызстан',
    main: 'Главная',
    promotion: 'Акции',
    contacts: 'Контакты',
    catalog: 'Каталог',
    catalogItem_1: 'Лекарства',
    catalogItem_2: 'Витамины и БАДы',
    catalogItem_3: 'Косметика',
    catalogItem_4: 'Гигиена',
    catalogItem_5: 'Медицинские изделия и приборы',
    catalogItem_6: 'Мама и малыш',
    catalogItem_7: 'Здоровое питание',
    catalogItem_8: 'Ортопедия',
    join: 'Войти',
    placeholder: 'Введите название товара, заболевания или симптома',
    heroTitle: 'MyPharm - онлайн аптека',
    sectionTitle_1: 'Акции и предложения',
    sectionTitle_2: 'Каталог',
    sectionTitle_3: 'Фармацевтические компании',
    allProducts: 'Все продукты',
    manifacturer: 'Производитель',
    price: 'Цена',
    kgs: 'сом',
    basket: 'В корзину',
    catalogButton: 'Перейти в каталог',
    aboutCompany: 'О компании',
    aboutUs: 'О нас',
    license: 'Лицензия и реквизиты',
    purveryor: 'Поставщики',
    service: 'Сервис',
    termsOfUse: 'Пользовательское соглашение',
    privacyPolicy: 'Политика конфиденциальности',
    comment: 'Отзывы',
    help: 'Помощь',
    FAQ: 'Часто задаваемые вопросы',
    order: 'Как сделать заказ',
    feedback: 'Обратная связь',
    delivery: 'Доставка',
    payment: 'Оплата',
    copyright: 'Интернет магазин',
    copyrightText:
      'Информация на сайте носит ознакомительный характер и не может служить заменой очной консультации врача',
  },
  EN: {
    location: 'Kyrgyzstan',
    main: 'Main',
    promotion: 'Promotions',
    contacts: 'Contacts',
    catalog: 'Catalog',
    catalogItem_1: 'Medications',
    catalogItem_2: 'Vitamins and dietary supplements',
    catalogItem_3: 'Cosmetics',
    catalogItem_4: 'Hygiene',
    catalogItem_5: 'Medical products and devices',
    catalogItem_6: 'Mom and baby',
    catalogItem_7: 'Healthy eating',
    catalogItem_8: 'Orthopedics',
    join: 'Sign in',
    placeholder: 'Enter the name of the product, disease or symptom',
    heroTitle: 'MyPharm - online pharmacy',
    sectionTitle_1: 'Promotions and offers',
    sectionTitle_2: 'Catalog',
    sectionTitle_3: 'Pharmaceutical companies',
    allProducts: 'All products',
    manifacturer: 'Manifacturer',
    price: 'Price',
    kgs: 'kgs',
    addToCard: 'Add to cart',
    basket: 'basket',
    catalogButton: 'Go to catalog',
    aboutCompany: 'About company',
    aboutUs: 'About us',
    license: 'License and details',
    purveryor: 'Perveryor',
    service: 'Service',
    termsOfUse: 'Terms of use',
    privacyPolicy: 'Privacy policy',
    comment: 'Comment',
    help: 'Help',
    FAQ: 'FAQ',
    order: 'How to make an order',
    feedback: 'Feedback',
    delivery: 'Delivery',
    payment: 'Payment',
    copyright: 'Internet shop',
    copyrightText:
      'The information on this website is for informational purposes only and is not a substitute for an in-person medical consultation.',
  },
  KG: {
    location: 'Кыргызстан',
    main: 'Башкы бет',
    promotion: 'Акциялар',
    contacts: 'Байланыш',
    catalog: 'Каталог',
    catalogItem_1: 'Дары-дармектер',
    catalogItem_2: 'Витаминдер жана БАДдар',
    catalogItem_3: 'Косметика',
    catalogItem_4: 'Гигиена',
    catalogItem_5: 'Медициналык буюмдар жана аппараттар',
    catalogItem_6: 'Эне жана бала',
    catalogItem_7: 'Туура тамактануу',
    catalogItem_8: 'Ортопедия',
    join: 'Кирүү',
    placeholder: 'Продукттун атын, ооруну же симптомду киргизиңиз',
    heroTitle: 'MyPharm - онлайн аптека',
    sectionTitle_1: 'Акциялар жана сунуштар',
    sectionTitle_2: 'Каталог',
    sectionTitle_3: 'Фармацевтикалык компаниялар',
    allProducts: 'Бардык продуктылар',
    manifacturer: 'Өндүрүүчү',
    price: 'Баа',
    kgs: 'сом',
    basket: 'Корзинага',
    catalogButton: 'Каталогго өтүү',
    aboutCompany: 'Компания жөнүндө',
    aboutUs: 'Биз жөнүндө',
    license: 'Лицензия жана маалымат',
    purveryor: 'Жабдуучулар',
    service: 'Сервис',
    termsOfUse: 'Пайдалануу шарттары',
    privacyPolicy: 'Купуялык саясаты',
    comment: 'Ой-пикирлер',
    help: 'Жардам',
    FAQ: 'Көп берилүүчү суроолор',
    order: 'Кантип заказ кылса болот',
    feedback: 'Кайтарым байланыш',
    delivery: 'Жеткирүү',
    payment: 'Төлөм',
    copyright: 'Интернет магазин',
    copyrightText:
      'Бул сайттагы маалымат маалыматтык максатта гана болуп саналат жана жеке медициналык консультацияны алмаштыра албайт.',
  },
};
