export const translateLang3 = {
  RU: {
    catigoryLists: [
      { value: 'Лекарства', href: '/medicine', id: '1' },
      { value: 'Витамины и БАДы', href: '/vitamins', id: '2' },
      { value: 'Косметика', href: '/cosmetics', id: '3' },
      { value: 'Гигиена', href: '/guinea', id: '4' },
      { value: 'Медицинские изделия и приборы', href: '/tools', id: '5' },
      { value: 'Мама и малыш', href: '/baby', id: '6' },
      { value: 'Ортопедия', href: '/orthopedics', id: '7' },
    ],
    location: 'Кыргызстан',
    main: 'Главная',
    promotion: 'Акции',
    contacts: 'Контакты',
    catalog: 'Каталог',
    catalogItem_1: 'Лекарства',
    catalogItem_2: 'Витамины и БАДы',
    catalogItem_3: 'Косметика',
    catalogItem_4: 'Гигиена',
    catalogItem_5: 'Медицинские изделия и приборы',
    catalogItem_6: 'Мама и малыш',
    catalogItem_7: 'Здоровое питание',
    catalogItem_8: 'Ортопедия',
    join: 'Войти',
    exit: 'Выйти',
    placeholder: 'Введите название товара, заболевания или симптома',
    search: 'Поиск',
    heroTitle: 'MyPharm - онлайн аптека',
    heroSubTitle:
      'Интернет-аптека MyPharm предоставляет множество возможностей для поиска и заказа нужных лекарств',
    sectionTitle_1: 'Акции и предложения',
    sectionTitle_3: 'Фармацевтические компании',
    allProducts: 'Все продукты',
    manifacturer: 'Производитель',
    price: 'Цена',
    kgs: 'сом',
    basket: 'В корзину',
    basketOne: 'Корзина',
    catalogButton: 'Перейти в каталог',
    aboutCompany: 'О компании',
    aboutUs: 'О нас',
    license: 'Лицензия и реквизиты',
    purveryor: 'Поставщики',
    service: 'Сервис',
    termsOfUse: 'Пользовательское соглашение',
    privacyPolicy: 'Политика конфиденциальности',
    comment: 'Отзывы',
    help: 'Помощь',
    FAQ: 'Часто задаваемые вопросы',
    order: 'Как сделать заказ',
    feedback: 'Обратная связь',
    delivery: 'Доставка',
    payment: 'Оплата',
    copyright: 'Интернет магазин',
    copyrightText:
      'Информация на сайте носит ознакомительный характер и не может служить заменой очной консультации врача',
    prescription: 'по рецепту',
    another: 'другой',
    pills: 'таблетки',
    powder: 'порошок',
    capsule: 'капсула',
    syrup: 'сироп',
    ampoule: 'ампула',
    spray: 'спрей',
    ointment: 'мазь',
    adult: 'взрослым',
    child: 'детям',
    pregnant: 'беременным',
    russia: 'Россия',
    kyrgystan: 'Кыргызстан',
    germany: 'Германия',
    france: 'Франция',
    kz: 'Казакстан',
    izrail: 'Израиль',
    koreya: 'Корея',
    usa: 'США',
    india: 'Индия',
    country: 'страна',
    appointments: 'назначения',
    accordingReleaseForm: 'По форма выпуска',
    clear: 'очистить',
    productСategories: 'Категории товаров',
    vacationOrder: 'Порядок отпуска',
    article: 'Артикуль',
    change: 'изменить',
    buyNow: 'Купить сейчас',
    pharmacyName: 'Название аптеки',
    similarProducts: 'Похожие товары',
    toHomePage: 'На главную страницу',
    basketEmpty: 'Ваша корзина пуста',
    basketEmptyText: 'Начните поиск и добавьте товар в корзину',
    goods: 'товара',
    goods2: 'товары',
    emptyTrash: 'Очистить корзину',
    informationOrder: 'Информация о заказе',
    outcome: 'Итог',
    orderProducts: 'Заказать',
    paymentMethod: 'Способ оплаты',
    notAddedMail: 'На данный момент вы еще не добавили товаров',
    favorites: 'Избранное',
    myOrders: 'Мои заказы',
    personalData: 'Личные данные',
    connectWithUs: 'Связаться с нами',
    questionsRelated: 'По вопросам связанным с оформлением, исполнение заказа вы можете обратиться',
    telephone: 'Телефон',
    anyQuestions:
      'Если у Вас есть вопросы и пожелания по работе сайта, контакт-центра или службы доставки, воспользуйтесь формой обратной связи:',
    name: 'Имя',
    yourName: 'Ваше имя',
    phoneNumber: 'Номер телефона',
    mail: 'Сообщение',
    send: 'Отправить',
  },
  EN: {
    catigoryLists: [
      { value: 'Medicines', href: '/medicine', id: '1' },
      { value: 'Vitamins and dietary supplements', href: '/vitamins', id: '2' },
      { value: 'Cosmetics', href: '/cosmetics', id: '3' },
      { value: 'Hygiene', href: '/guinea', id: '4' },
      { value: 'Medical products and devices', href: '/tools', id: '5' },
      { value: 'Mom and baby', href: '/baby', id: '6' },
      { value: 'Orthopedics', href: '/orthopedics', id: '7' },
    ],
    location: 'Kyrgyzstan',
    main: 'Main',
    promotion: 'Promotions',
    contacts: 'Contacts',
    catalog: 'Catalog',
    catalogItem_1: 'Medications',
    catalogItem_2: 'Vitamins and dietary supplements',
    catalogItem_3: 'Cosmetics',
    catalogItem_4: 'Hygiene',
    catalogItem_5: 'Medical products and devices',
    catalogItem_6: 'Mom and baby',
    catalogItem_7: 'Healthy eating',
    catalogItem_8: 'Orthopedics',
    catalogItem_all: 'All products',
    join: 'Sign in',
    exit: 'Exit',
    placeholder: 'Enter the name of the product, disease or symptom',
    search: 'Search',
    heroTitle: 'MyPharm - online pharmacy',
    heroSubTitle:
      'MyPharm online pharmacy provides many options for finding and ordering the right medicines',
    sectionTitle_1: 'Promotions and offers',
    sectionTitle_3: 'Pharmaceutical companies',
    allProducts: 'All products',
    manifacturer: 'Manifacturer',
    price: 'Price',
    kgs: 'kgs',
    addToCard: 'Add to cart',
    basket: 'basket',
    basketOne: 'Basket',
    catalogButton: 'Go to catalog',
    aboutCompany: 'About company',
    aboutUs: 'About us',
    license: 'License and details',
    purveryor: 'Perveryor',
    service: 'Service',
    termsOfUse: 'Terms of use',
    privacyPolicy: 'Privacy policy',
    comment: 'Comment',
    help: 'Help',
    FAQ: 'FAQ',
    order: 'How to make an order',
    feedback: 'Feedback',
    delivery: 'Delivery',
    payment: 'Payment',
    copyright: 'Internet shop',
    copyrightText:
      'The information on this website is for informational purposes only and is not a substitute for an in-person medical consultation.',
    prescription: 'on prescription',
    another: 'another',
    pills: 'pills',
    powder: 'powder',
    capsule: 'capsule',
    syrup: 'syrup',
    ampoule: 'ampoule',
    spray: 'spray',
    ointment: 'ointment',
    adult: 'adult',
    child: 'child',
    pregnant: 'pregnant',
    russia: 'Russia',
    kyrgystan: 'Kyrgystan',
    germany: 'Germany',
    france: 'France',
    kz: 'Kazakhstan',
    izrail: 'Izrail',
    koreya: 'Koreya',
    usa: 'USA',
    india: 'India',
    country: 'country',
    appointments: 'appointments',
    accordingReleaseForm: 'According to release form',
    clear: 'clear',
    productСategories: 'Product categories',
    vacationOrder: 'Vacation order',
    article: 'Article',
    change: 'change',
    buyNow: 'Buy now',
    pharmacyName: 'Pharmacy name',
    similarProducts: 'Similar products',
    toHomePage: 'to Home Page',
    basketEmpty: 'your basket is empty',
    basketEmptyText: 'Start your search and add the item to your shopping cart',
    goods: 'goods',
    goods2: 'Goods',
    emptyTrash: 'Empty trash',
    informationOrder: 'Information about order',
    outcome: 'Outcome',
    orderProducts: 'Order',
    paymentMethod: 'Payment method',
    notAddedMail: 'You have not added any products at the moment',
    favorites: 'Favorites',
    myOrders: 'My orders',
    personalData: 'Personal data',
    connectWithUs: 'Connect with us',
    questionsRelated:
      'For questions related to the execution, execution of the order, you can contact',
    telephone: 'Telephone',
    anyQuestions:
      'If you have any questions or suggestions regarding the operation of the site, contact center or service delivery, use the feedback form:',
    name: 'Name',
    yourName: 'Your name',
    phoneNumber: 'Phone number',
    mail: 'Mail',
    send: 'Send',
  },
  KG: {
    catigoryLists: [
      { value: 'Дарылар', href: '/medicine', id: '1' },
      { value: 'Витаминдер жана диеталык кошумчалар', href: '/vitamins', id: '2' },
      { value: 'Косметика', href: '/cosmetics', id: '3' },
      { value: 'Гигиена', href: '/guinea', id: '4' },
      { value: 'Медициналык продуктулар жана түзмөктөр', href: '/tools', id: '5' },
      { value: 'Эне жана бала', href: '/baby', id: '6' },
      { value: 'Ортопедия', href: '/orthopedics', id: '7' },
    ],
    location: 'Кыргызстан',
    main: 'Башкы бет',
    promotion: 'Акциялар',
    contacts: 'Байланыш',
    catalog: 'Каталог',
    catalogItem_1: 'Дары-дармектер',
    catalogItem_2: 'Витаминдер жана БАДдар',
    catalogItem_3: 'Косметика',
    catalogItem_4: 'Гигиена',
    catalogItem_5: 'Медициналык буюмдар жана аппараттар',
    catalogItem_6: 'Эне жана бала',
    catalogItem_7: 'Туура тамактануу',
    catalogItem_8: 'Ортопедия',
    catalogItem_all: 'Бардык таварлар',
    join: 'Кирүү',
    exit: 'Чыгуу',
    placeholder: 'Продукттун атын, ооруну же симптомду киргизиңиз',
    search: 'Издөө',
    heroTitle: 'MyPharm - онлайн аптека',
    heroSubTitle:
      'MyPharm онлайн дарыканасы туура дарыларды табуу жана заказ кылуу үчүн көптөгөн мүмкүнчүлүктөрдү берет',
    sectionTitle_1: 'Акциялар жана сунуштар',
    sectionTitle_3: 'Фармацевтикалык компаниялар',
    allProducts: 'Бардык продуктылар',
    manifacturer: 'Өндүрүүчү',
    price: 'Баа',
    kgs: 'сом',
    basket: 'Корзинага',
    basketOne: 'Корзинага',
    catalogButton: 'Каталогго өтүү',
    aboutCompany: 'Компания жөнүндө',
    aboutUs: 'Биз жөнүндө',
    license: 'Лицензия жана маалымат',
    purveryor: 'Жабдуучулар',
    service: 'Сервис',
    termsOfUse: 'Пайдалануу шарттары',
    privacyPolicy: 'Купуялык саясаты',
    comment: 'Ой-пикирлер',
    help: 'Жардам',
    FAQ: 'Көп берилүүчү суроолор',
    order: 'Кантип заказ кылса болот',
    feedback: 'Кайтарым байланыш',
    delivery: 'Жеткирүү',
    payment: 'Төлөм',
    copyright: 'Интернет магазин',
    copyrightText:
      'Бул сайттагы маалымат маалыматтык максатта гана болуп саналат жана жеке медициналык консультацияны алмаштыра албайт.',
    prescription: 'рецепт боюнча',
    another: 'башка',
    pills: 'таблетка',
    powder: 'порошок',
    capsule: 'капсула',
    syrup: 'сироп',
    ampoule: 'ампула',
    spray: 'спрей',
    ointment: 'мазь',
    adult: 'чондорго',
    child: 'балдарга',
    pregnant: 'кош бойлууларга',
    russia: 'Орусия',
    kyrgystan: 'Кыргызстан',
    germany: 'Германия',
    france: 'Франция',
    kz: 'Казакстан',
    izrail: 'Израиль',
    koreya: 'Корея',
    usa: 'АКШ',
    india: 'Индия',
    country: 'мамлекет',
    appointments: 'дайындоолор',
    accordingReleaseForm: 'чыгаруу формасы боюнча',
    clear: 'тазалоо',
    productСategories: 'Продукт категориялары',
    vacationOrder: 'Чыгаруу тартиби',
    article: 'Артикуль',
    change: 'озгортуу',
    buyNow: 'Азыр сатып алуу',
    pharmacyName: 'Аптеканын аты',
    similarProducts: 'Окшош буюмдар',
    toHomePage: 'Башкы бетке',
    basketEmpty: 'Сиздин корзинаныз бош',
    basketEmptyText: 'Издөөнү баштап, товарды корзинага кошуңуз',
    goods: 'товар',
    goods2: 'Товарлар',
    emptyTrash: 'Корзинана тазалоо',
    informationOrder: 'Тартиби жөнүндө маалымат',
    outcome: 'Жыйынтык',
    orderProducts: 'Заказ',
    paymentMethod: 'Төлөө ыкмасы',
    notAddedMail: 'Учурда эч кандай өнүм кошкон жоксуз',
    favorites: 'Сүйүктүүлөр',
    myOrders: 'Менин заказдарым',
    personalData: 'Жеке маалыматтар',
    connectWithUs: 'Биз менен байланышуу',
    questionsRelated:
      'Буйруктун аткарылышы, аткарылышы боюнча суроолор боюнча кайрылсаңыздар болот',
    telephone: 'Телефон',
    anyQuestions:
      'Сайттын иштешине, байланыш борборуна же кызматка байланыштуу суроолоруңуз же сунуштарыңыз болсо жеткирүү, пикир формасын колдонуңуз:',
    name: 'Аты',
    yourName: 'Сиздин атыныз',
    phoneNumber: 'Телефон номуру',
    mail: 'Кат',
    send: 'Жонотуу',
  },
};
